-- MySQL Script generated by MySQL Workbench
-- Tue Jun 27 14:45:47 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`members` (
  `idmembers` INT NOT NULL,
  `fName` VARCHAR(45) NOT NULL,
  `lName` VARCHAR(45) NOT NULL,
  `phoneNumber` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `wont_talk` VARCHAR(45) NULL,
  PRIMARY KEY (`idmembers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bishopric`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bishopric` (
  `idbishopric` INT NOT NULL,
  `asking_bishopric` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idbishopric`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`talks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`talks` (
  `idtalks` INT NOT NULL AUTO_INCREMENT,
  `date` VARCHAR(45) NOT NULL,
  `topic` INT NOT NULL,
  `member` INT NOT NULL,
  `star` VARCHAR(45) NULL,
  `members_idmembers` INT NOT NULL,
  `asking_bishopric` INT NOT NULL,
  `bishopric_idbishopric` INT NOT NULL,
  PRIMARY KEY (`idtalks`),
  INDEX `fk_talks_members_idx` (`members_idmembers` ASC),
  INDEX `fk_talks_bishopric1_idx` (`bishopric_idbishopric` ASC),
  CONSTRAINT `fk_talks_members`
    FOREIGN KEY (`members_idmembers`)
    REFERENCES `mydb`.`members` (`idmembers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_talks_bishopric1`
    FOREIGN KEY (`bishopric_idbishopric`)
    REFERENCES `mydb`.`bishopric` (`idbishopric`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`topics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`topics` (
  `idtopics` INT NOT NULL,
  `speakingTopic` VARCHAR(45) NOT NULL,
  `talks_idtalks` INT NOT NULL,
  PRIMARY KEY (`idtopics`),
  INDEX `fk_topics_talks1_idx` (`talks_idtalks` ASC),
  CONSTRAINT `fk_topics_talks1`
    FOREIGN KEY (`talks_idtalks`)
    REFERENCES `mydb`.`talks` (`idtalks`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
